### ISSUE TITLE
This is awesome!

### ISSUE THREAD

**Issue by tomeichlersmith** [dguest/hdf5-ntuples#2]
Thank you so much for this! I am trying to drag the software I'm working on away from ROOT, and I can see a path forward with this!

:100: :100: :100: :rocket: :rocket: :tada: :tada:

**Comment by dguest** [comment]
Hi, glad you found it useful. I should say I've sort of moved away from using the HDF5 variable length type and started doing more of either:
 - keeping two datasets, one of "objects" which are variable length, and another for "events" which could contain any number of objects. The events dataset just keeps the indices of the first and last object that correspond to that event, or
 - zero padding fixed dimensional arrays. This isn't very clean but it works well with numpy and is sufficient in a lot of cases.

The code we currently use is [part of the ATLAS experiment's repository](https://gitlab.cern.ch/atlas/athena/-/tree/master/PhysicsAnalysis/AnalysisCommon/HDF5Utils). It's unfortunately a bit integrated with that (the CMake is heavily extended, at least), but it's a slightly more developed chunk of code that we use quite a bit.

**Comment by tomeichlersmith** [comment]
Thank you for your input :) I've been noticing that the var-len implementation is a little clunky, so thank you for another idea!
